#!/usr/bin/env node
/**
 * INFRA-12 (D-021 tier 1): Playwright-Electron smoke suite for ArDrive Desktop.
 *
 * Launches the REAL built app (dist/) headed (WSLg/X11 locally), drives the
 * full first-run flow through the real UI, and captures a screenshot at every
 * step into a per-run artifacts directory:
 *
 *   01 launch with a DISPOSABLE userData dir (ARDRIVE_TEST_USERDATA hook in
 *      src/main/main.ts — unpackaged builds only, fails closed when packaged)
 *   02 first-run wallet-setup screen renders
 *   03 wallet import via the existing dev-mode autofill (ARDRIVE_DEV_* env);
 *      the wallet is a fresh zero-fund throwaway generated by this script
 *   04 public drive creation + sync folder through the real UI
 *      (REAL on-chain ArFS metadata action via the Turbo free tier)
 *   05 drop a <100KB junk file into the sync folder -> approval queue shows it FREE
 *   06 approve through the real UI -> upload completes (REAL network, free tier)
 *   07 app quits cleanly
 *
 * MONEY RAIL (absolute): the wallet is generated fresh per run and NEVER
 * funded; the single test file is <100KB so every network write rides the
 * Turbo free tier. Nothing here references a funded wallet or paid path.
 *
 * Prereq: `npm run build` (dist/main + dist/renderer must exist).
 * Run:    `npm run smoke`
 * Output: tests/e2e/artifacts/<run-id>/ (screenshots, main/renderer logs,
 *         manifest.json). Wallet JSON, userData and the sync folder live in a
 *         disposable os.tmpdir() directory — never inside the repo.
 *
 * This file is intentionally OUTSIDE the vitest include glob
 * (tests/**\/*.test.{ts,tsx}) so `npm run test` never picks it up.
 */

/* eslint-disable no-console, @typescript-eslint/no-var-requires */
'use strict';

const fs = require('fs');
const fsp = require('fs/promises');
const os = require('os');
const path = require('path');
const { _electron: electron } = require('playwright');
const Arweave = require('arweave');

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------
const REPO_ROOT = path.resolve(__dirname, '..', '..');
const RUN_ID =
  new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19) +
  '-' +
  Math.random().toString(36).slice(2, 6);
const ARTIFACTS_DIR = path.join(__dirname, 'artifacts', RUN_ID);

const UI_TIMEOUT = 30_000; // pure-UI transitions
const IMPORT_TIMEOUT = 180_000; // wallet import + fresh-wallet drive listing (network)
// Drive create + initial metadata sync. arweave.net intermittently 429s with
// 60s backoff pauses (observed in run logs) — this step absorbs a few of them.
const DRIVE_CREATE_TIMEOUT = 420_000;
const QUEUE_TIMEOUT = 180_000; // watcher-active gate + detection (3s window) + 5s UI poll
const UPLOAD_TIMEOUT = 240_000; // real network upload, free tier

// Drive name must satisfy /^[a-zA-Z0-9\s\-_]*$/ and <= 32 chars.
const DRIVE_NAME = `smoke-test-${RUN_ID.slice(-4)}-${Date.now().toString(36).slice(-4)}`;
// Throwaway password for a throwaway zero-fund wallet (min 8 chars).
const PASSWORD = `Smoke-${RUN_ID}`;

// ---------------------------------------------------------------------------
// Step bookkeeping: every step ends in a screenshot; the manifest is written
// no matter how the run ends.
// ---------------------------------------------------------------------------
const manifest = {
  runId: RUN_ID,
  startedAt: new Date().toISOString(),
  driveName: DRIVE_NAME,
  walletAddress: null,
  steps: [],
  result: 'incomplete'
};
let stepCounter = 0;
let page = null; // current Playwright Page, once available
let electronAppRef = null; // for signal-time cleanup

// If the runner is killed from outside (e.g. a CI/job timeout), still leave an
// honest manifest + dead app behind instead of vanishing mid-run.
function finalizeOnSignal(signal, exitCode) {
  try {
    manifest.result = `killed-${signal.toLowerCase()}`;
    manifest.finishedAt = new Date().toISOString();
    fs.mkdirSync(ARTIFACTS_DIR, { recursive: true });
    fs.writeFileSync(path.join(ARTIFACTS_DIR, 'manifest.json'), JSON.stringify(manifest, null, 2));
  } catch { /* best effort */ }
  try {
    electronAppRef?.process().kill('SIGKILL');
  } catch { /* best effort */ }
  process.exit(exitCode);
}
process.on('SIGTERM', () => finalizeOnSignal('SIGTERM', 124));
process.on('SIGINT', () => finalizeOnSignal('SIGINT', 130));

async function screenshot(label) {
  const file = path.join(ARTIFACTS_DIR, `${label}.png`);
  try {
    if (page && !page.isClosed()) {
      await page.screenshot({ path: file, timeout: 10_000 });
      return file;
    }
  } catch (err) {
    console.warn(`  (screenshot ${label} failed: ${err.message})`);
  }
  return null;
}

async function step(name, fn, { blockedIsFailure = true } = {}) {
  stepCounter += 1;
  const label = `${String(stepCounter).padStart(2, '0')}-${name}`;
  const entry = { step: label, status: 'running', startedAt: new Date().toISOString() };
  manifest.steps.push(entry);
  console.log(`\n=== STEP ${label} ===`);
  try {
    const detail = await fn();
    entry.status = 'pass';
    if (detail) entry.detail = detail;
    entry.screenshot = await screenshot(label);
    console.log(`PASS ${label}${detail ? ` — ${detail}` : ''}`);
  } catch (err) {
    const blocked = err && err.smokeBlocked === true;
    entry.status = blocked ? 'blocked' : 'fail';
    entry.error = err && err.message ? err.message : String(err);
    entry.screenshot = await screenshot(`${label}-${entry.status.toUpperCase()}`);
    console.error(`${entry.status.toUpperCase()} ${label}: ${entry.error}`);
    if (blocked && !blockedIsFailure) return;
    const e = new Error(`Step ${label} ${entry.status}: ${entry.error}`);
    e.smokeStepFailed = true;
    throw e;
  } finally {
    entry.finishedAt = new Date().toISOString();
  }
}

/** Error subtype for "the app told us no" (e.g. Turbo rejected the zero-fund
 *  wallet) — evidence is captured, the run stops honestly. */
function blockedError(message) {
  const e = new Error(message);
  e.smokeBlocked = true;
  return e;
}

/** Poll an async predicate until truthy or timeout. Errors thrown by the
 *  predicate are retried unless marked `smokeAbort` (terminal condition). */
async function waitUntil(fn, { timeout, interval = 1_000, description }) {
  const deadline = Date.now() + timeout;
  let lastErr = null;
  for (;;) {
    try {
      const value = await fn();
      if (value) return value;
    } catch (err) {
      if (err && err.smokeAbort) throw err;
      lastErr = err;
    }
    if (Date.now() > deadline) {
      throw new Error(
        `Timed out after ${timeout}ms waiting for: ${description}` +
          (lastErr ? ` (last error: ${lastErr.message})` : '')
      );
    }
    await new Promise((r) => setTimeout(r, interval));
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function main() {
  // -- Preflight -------------------------------------------------------------
  const mainEntry = path.join(REPO_ROOT, 'dist', 'main', 'main.js');
  const rendererEntry = path.join(REPO_ROOT, 'dist', 'renderer', 'index.html');
  if (!fs.existsSync(mainEntry) || !fs.existsSync(rendererEntry)) {
    console.error(
      'dist/ build not found. Run `npm run build` first — the smoke suite drives the real built app.'
    );
    process.exit(2);
  }
  if (!process.env.DISPLAY && process.platform === 'linux') {
    console.warn(
      'WARNING: DISPLAY is not set. The suite launches the app HEADED; under WSL it needs WSLg (DISPLAY=:0) or an X server/xvfb.'
    );
  }

  await fsp.mkdir(ARTIFACTS_DIR, { recursive: true });

  // -- Disposable world: userData, sync folder, throwaway wallet -------------
  const tmpRoot = await fsp.mkdtemp(path.join(os.tmpdir(), 'ardrive-smoke-'));
  const userDataDir = path.join(tmpRoot, 'userdata');
  const syncRoot = path.join(tmpRoot, 'sync');
  const walletPath = path.join(tmpRoot, 'wallet.json');
  await fsp.mkdir(userDataDir, { recursive: true });
  await fsp.mkdir(syncRoot, { recursive: true });

  console.log(`Run id:        ${RUN_ID}`);
  console.log(`Artifacts:     ${ARTIFACTS_DIR}`);
  console.log(`Disposable dir: ${tmpRoot}`);

  // Fresh zero-fund wallet, generated locally. Never committed, never funded.
  const arweave = Arweave.init({});
  const jwk = await arweave.wallets.generate();
  const address = await arweave.wallets.jwkToAddress(jwk);
  await fsp.writeFile(walletPath, JSON.stringify(jwk), { mode: 0o600 });
  manifest.walletAddress = address;
  console.log(`Wallet:        ${address} (freshly generated, zero funds)`);

  // -- Launch the real built app ---------------------------------------------
  const mainLog = fs.createWriteStream(path.join(ARTIFACTS_DIR, 'main-process.log'));
  const rendererLog = fs.createWriteStream(path.join(ARTIFACTS_DIR, 'renderer-console.log'));

  const electronApp = await electron.launch({
    cwd: REPO_ROOT,
    args: ['.'],
    timeout: 120_000,
    env: {
      ...process.env,
      // production => no auto-opened DevTools polluting the screenshots;
      // dev-mode autofill is gated on ARDRIVE_DEV_MODE + !isPackaged, not NODE_ENV.
      NODE_ENV: 'production',
      ARDRIVE_TEST_USERDATA: userDataDir,
      ARDRIVE_DEV_MODE: 'true',
      ARDRIVE_DEV_WALLET_PATH: walletPath,
      ARDRIVE_DEV_PASSWORD: PASSWORD,
      ARDRIVE_DEV_SYNC_FOLDER: syncRoot
    }
  });
  electronAppRef = electronApp;
  electronApp.process().stdout?.on('data', (d) => mainLog.write(d));
  electronApp.process().stderr?.on('data', (d) => mainLog.write(d));

  // Opportunistic toast evidence: screenshot each new toast as it appears.
  let toastShots = 0;
  let toastWatcher = null;
  const watchToasts = () => {
    toastWatcher = setInterval(async () => {
      try {
        if (!page || page.isClosed() || toastShots >= 8) return;
        const toasts = await page.locator('.toast-notification').count();
        if (toasts > 0) {
          toastShots += 1;
          const file = path.join(ARTIFACTS_DIR, `toast-${toastShots}.png`);
          await page.screenshot({ path: file, timeout: 5_000 });
          const text = await page.locator('.toast-notification').first().innerText().catch(() => '');
          manifest.steps.push({
            step: `toast-${toastShots}`,
            status: 'evidence',
            detail: text.replace(/\s+/g, ' ').trim(),
            screenshot: file
          });
          console.log(`  [toast] ${text.replace(/\s+/g, ' ').trim()}`);
          // let the toast disappear before we look again, to avoid duplicates
          await new Promise((r) => setTimeout(r, 6_000));
        }
      } catch {
        /* non-fatal evidence collection */
      }
    }, 1_500);
  };

  let runFailed = false;
  try {
    page = await electronApp.firstWindow({ timeout: 120_000 });
    page.setDefaultTimeout(UI_TIMEOUT);
    page.on('console', (msg) => rendererLog.write(`[${msg.type()}] ${msg.text()}\n`));
    watchToasts();

    // ---- 01: disposable userData actually in effect ------------------------
    await step('launch-disposable-userdata', async () => {
      const effective = await electronApp.evaluate(({ app }) => app.getPath('userData'));
      if (effective !== userDataDir) {
        throw new Error(
          `userData hook not in effect: expected ${userDataDir}, app reports ${effective}`
        );
      }
      await page.waitForLoadState('domcontentloaded');
      return `userData=${effective}`;
    });

    // ---- 02: first-run wallet setup renders --------------------------------
    await step('first-run-wallet-setup', async () => {
      await page
        .getByRole('heading', { name: 'Welcome to ArDrive Desktop' })
        .waitFor({ state: 'visible', timeout: UI_TIMEOUT });
      await page
        .getByRole('button', { name: /Import Existing Account/ })
        .waitFor({ state: 'visible' });
    });

    // ---- 03: import form autofilled by dev mode ----------------------------
    await step('import-form-autofilled', async () => {
      await page.getByRole('button', { name: /Import Existing Account/ }).click();
      // Dev-mode autofill populates wallet path + password asynchronously.
      await page.getByText('wallet.json', { exact: false }).first().waitFor({ timeout: UI_TIMEOUT });
      const importButton = page.getByRole('button', { name: 'Import Wallet' });
      await waitUntil(() => importButton.isEnabled(), {
        timeout: UI_TIMEOUT,
        description: 'Import Wallet button enabled (autofill complete)'
      });
      return 'wallet path + password autofilled from ARDRIVE_DEV_* env';
    });

    // ---- 04: import wallet -> drive setup ----------------------------------
    await step('wallet-imported-drive-setup', async () => {
      await page.getByRole('button', { name: 'Import Wallet' }).click();
      // Fresh wallet has no drives. Depending on timing the app either
      // auto-navigates to drive setup, or rests on the welcome-back screen's
      // "No drives found" empty state — a real user clicks Create New Public
      // Drive there, so the harness does too.
      const driveSetupHeading = page.getByRole('heading', {
        name: /Create a New Drive|Set Up Your Storage/
      });
      const createNewDriveButton = page.getByRole('button', { name: /Create New Public Drive/ });
      await driveSetupHeading
        .or(createNewDriveButton)
        .first()
        .waitFor({ state: 'visible', timeout: IMPORT_TIMEOUT });
      let detail = 'reached drive-setup step directly (no existing drives for fresh wallet)';
      if (await createNewDriveButton.isVisible().catch(() => false)) {
        await screenshot('04a-welcome-back-no-drives');
        await createNewDriveButton.click();
        await driveSetupHeading.waitFor({ state: 'visible', timeout: UI_TIMEOUT });
        detail =
          'welcome-back showed "No drives found" for fresh wallet; clicked Create New Public Drive to reach drive setup';
      }
      return detail;
    });

    // ---- 05: fill drive form (name + autofilled sync folder) ---------------
    await step('drive-form-filled', async () => {
      await page.getByPlaceholder('e.g., Personal Files, Work Documents').fill(DRIVE_NAME);
      // sync folder was autofilled from ARDRIVE_DEV_SYNC_FOLDER
      await page.getByText(syncRoot, { exact: false }).first().waitFor({ timeout: UI_TIMEOUT });
      return `drive name "${DRIVE_NAME}", sync folder ${syncRoot}`;
    });

    // ---- 06: review summary -------------------------------------------------
    await step('review-summary', async () => {
      await page.getByRole('button', { name: 'Continue to Review' }).click();
      await page.getByRole('heading', { name: 'Review Your Setup' }).waitFor({ timeout: UI_TIMEOUT });
      await page.getByText(DRIVE_NAME, { exact: false }).first().waitFor();
      await page.getByText('Public Drive', { exact: false }).first().waitFor();
    });

    // ---- 07: create the drive (REAL on-chain ArFS metadata, Turbo free) ----
    // With auto-sync enabled (product default) this step covers drive creation
    // AND the initial metadata sync + sync-engine start. The sync phase is
    // where arweave.net 429 backoff bites, so while waiting we save interim
    // evidence screenshots every 60s instead of going dark.
    await step('drive-created-on-chain', async () => {
      await page.getByRole('button', { name: 'Complete Setup' }).click();
      const success = page.getByRole('heading', { name: /Your Drive Is Ready/ });
      const failure = page.locator('.error-message');
      const deadline = Date.now() + DRIVE_CREATE_TIMEOUT;
      let lastShot = Date.now();
      let interim = 0;
      for (;;) {
        if (await success.isVisible().catch(() => false)) break;
        if (await failure.isVisible().catch(() => false)) {
          const text = (await failure.innerText()).replace(/\s+/g, ' ').trim();
          throw blockedError(
            `Drive creation rejected (zero-fund wallet on real network): "${text}"`
          );
        }
        if (Date.now() > deadline) {
          throw new Error(
            `no success screen or error after ${DRIVE_CREATE_TIMEOUT}ms — drive create + initial sync still pending; check main-process.log for gateway 429 rate limiting`
          );
        }
        if (Date.now() - lastShot >= 60_000) {
          interim += 1;
          lastShot = Date.now();
          await screenshot(`07-waiting-${interim}`);
        }
        await page.waitForTimeout(3_000);
      }
      return `public drive "${DRIVE_NAME}" created on-chain via Turbo free tier (zero-fund wallet)`;
    });

    // ---- 08: dashboard ------------------------------------------------------
    await step('dashboard-loaded', async () => {
      await page.getByRole('button', { name: /Open Dashboard/ }).click();
      await page
        .getByRole('tab', { name: /Upload Queue/ })
        .waitFor({ state: 'visible', timeout: IMPORT_TIMEOUT });
    });

    // ---- 09: drop a junk file into the synced drive folder -----------------
    const junkName = `smoke-junk-${RUN_ID}.txt`;
    const driveFolder = path.join(syncRoot, DRIVE_NAME);
    await step('junk-file-dropped', async () => {
      await waitUntil(() => fs.existsSync(driveFolder), {
        timeout: UI_TIMEOUT,
        description: `drive sync folder created at ${driveFolder}`
      });
      // The watcher ignores files that exist before it starts
      // (chokidar ignoreInitial) — gate the drop on the sync engine being
      // active, via the real preload IPC as ground truth.
      await waitUntil(
        async () => {
          const status = await page.evaluate(() => window.electronAPI.sync.getStatus());
          return status && status.isActive === true;
        },
        { timeout: QUEUE_TIMEOUT, interval: 3_000, description: 'sync engine active (file watcher live)' }
      );
      await page.waitForTimeout(2_000); // let chokidar finish arming
      const contents =
        `ardrive smoke test ${new Date().toISOString()}\n` +
        `run ${RUN_ID} — disposable junk content, safe to ignore\n`.repeat(20);
      const junkPath = path.join(driveFolder, junkName);
      await fsp.writeFile(junkPath, contents);
      const size = (await fsp.stat(junkPath)).size;
      if (size >= 100 * 1024) throw new Error(`junk file unexpectedly >=100KB (${size} bytes)`);
      return `${junkName} (${size} bytes, <100KB free tier)`;
    });

    // ---- 10: file appears in approval queue as FREE -------------------------
    await step('approval-queue-shows-free', async () => {
      // Ground truth first: the pending-upload record via the real preload IPC.
      const pending = await waitUntil(
        async () => {
          // UX-3 (D-005): uploads:get-pending returns the IpcResult envelope.
          const res = await page.evaluate(() => window.electronAPI.uploads.getPending());
          const rows = res && res.success ? res.data : [];
          return Array.isArray(rows) && rows.find((r) => r.fileName === junkName);
        },
        { timeout: QUEUE_TIMEOUT, interval: 3_000, description: `${junkName} in pending uploads` }
      );
      // Then the UI: open the queue tab and confirm the row + FREE badge.
      await page.getByRole('tab', { name: /Upload Queue/ }).click();
      await page.getByText(junkName, { exact: false }).first().waitFor({ timeout: QUEUE_TIMEOUT });
      await page
        .getByText(/^(FREE|Free)$/)
        .first()
        .waitFor({ timeout: UI_TIMEOUT });
      return `pending upload id=${pending.id}, size=${pending.fileSize} bytes, shown as FREE`;
    });

    // ---- 11: approve through the real UI ------------------------------------
    await step('upload-approved', async () => {
      await page.getByRole('button', { name: /Approve & Upload/ }).click();
      // small settle so the post-click state (uploading) is what we capture
      await page.waitForTimeout(2_000);
    });

    // ---- 12: upload completes (REAL network, free tier) ---------------------
    await step('upload-completed', async () => {
      const uploaded = await waitUntil(
        async () => {
          const uploads = await page.evaluate(() => window.electronAPI.files.getUploads());
          const row = (uploads || []).find((u) => u.fileName === junkName);
          if (row && row.status === 'failed') {
            const e = new Error(`upload failed: ${row.error || 'no error detail recorded'}`);
            e.smokeAbort = true; // terminal — do not keep polling
            throw e;
          }
          return row && row.status === 'completed' ? row : null;
        },
        { timeout: UPLOAD_TIMEOUT, interval: 5_000, description: `${junkName} upload completed` }
      );
      return `upload completed, tx=${uploaded.transactionId || uploaded.dataTxId || 'n/a'}`;
    });

    // ---- 13: completion visible in Activity view ----------------------------
    await step('activity-shows-completed', async () => {
      await page.getByRole('tab', { name: /Activity/ }).click();
      await page.getByText(junkName, { exact: false }).first().waitFor({ timeout: UI_TIMEOUT });
      await page.getByText('uploaded to', { exact: false }).first().waitFor({ timeout: UI_TIMEOUT });
    });

    // ---- 14: permaweb view (evidence screenshot; content is soft-asserted) --
    await step(
      'permaweb-view',
      async () => {
        await page.getByRole('tab', { name: /Permaweb/ }).click();
        await page.waitForTimeout(3_000); // let it render/fetch before evidence shot
        const seen = await page
          .getByText(junkName, { exact: false })
          .first()
          .isVisible()
          .catch(() => false);
        return seen
          ? 'uploaded file visible in permaweb view'
          : 'permaweb tab rendered (file row not visible yet — metadata refresh lag, screenshot captured)';
      },
      { blockedIsFailure: false }
    );

    // ---- 15: clean quit ------------------------------------------------------
    await step('app-quits-cleanly', async () => {
      // final full-window shot happens in the step wrapper before close below
      await screenshot('15-pre-quit-final-state');
      await electronApp.close();
      page = null;
      await waitUntil(() => electronApp.process().exitCode !== null, {
        timeout: 30_000,
        description: 'electron main process exit'
      });
      return `exit code ${electronApp.process().exitCode}`;
    });

    manifest.result = 'pass';
  } catch (err) {
    runFailed = true;
    if (!err.smokeStepFailed) {
      console.error(`\nUnexpected harness error: ${err.stack || err.message}`);
      manifest.steps.push({ step: 'harness-error', status: 'fail', error: String(err.message) });
      await screenshot('harness-error');
    }
    manifest.result = manifest.steps.some((s) => s.status === 'blocked') ? 'blocked' : 'fail';
  } finally {
    if (toastWatcher) clearInterval(toastWatcher);
    // Ensure the app is gone even after a failure.
    try {
      if (electronApp.process().exitCode === null) {
        await electronApp.close().catch(() => {});
        setTimeout(() => {
          try {
            electronApp.process().kill('SIGKILL');
          } catch { /* already gone */ }
        }, 10_000).unref();
      }
    } catch { /* already gone */ }
    mainLog.end();
    rendererLog.end();

    manifest.finishedAt = new Date().toISOString();
    const manifestPath = path.join(ARTIFACTS_DIR, 'manifest.json');
    await fsp.writeFile(manifestPath, JSON.stringify(manifest, null, 2));

    // Best-effort cleanup of the disposable world (wallet, userData, sync dir).
    await fsp.rm(tmpRoot, { recursive: true, force: true }).catch(() => {});

    console.log('\n================ SMOKE RESULT ================');
    console.log(`Result:   ${manifest.result.toUpperCase()}`);
    console.log(`Manifest: ${manifestPath}`);
    for (const s of manifest.steps) {
      console.log(
        `  [${(s.status || '?').padEnd(8)}] ${s.step}` +
          (s.screenshot ? `\n             ${s.screenshot}` : '') +
          (s.error ? `\n             ERROR: ${s.error}` : '')
      );
    }
    console.log('==============================================');
  }

  process.exit(runFailed ? 1 : 0);
}

main().catch((err) => {
  console.error('Fatal harness error:', err);
  process.exit(1);
});
