name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            arch: x64
          - os: macos-latest
            platform: macos
            arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: x64

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Build Electron app for ${{ matrix.platform }}
      run: npm run dist
      env:
        # Disable code signing for now
        CSC_IDENTITY_AUTO_DISCOVERY: false
        # Prevent auto-publish to GitHub releases for now
        ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true

    - name: List release files
      run: |
        echo "Built files:"
        ls -la release/ || echo "No release folder found"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ArDrive-Desktop-${{ matrix.platform }}-${{ matrix.arch }}
        path: |
          release/*.exe
          release/*.dmg
          release/*.AppImage
          release/*.deb
          release/*.zip
          release/*.tar.gz
        retention-days: 30
        if-no-files-found: warn

  create-release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Display structure of downloaded files
      run: |
        echo "Downloaded artifacts:"
        find artifacts -type f -exec ls -la {} \;

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/**/*
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}